dwhprojeto:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dpg-cpmvefg8fa8c73apc0v0-a.oregon-postgres.render.com
      user: postgres123
      password: srwFrBrIDMJcOI56r2rcwwp5GwmYDuXD
      port: 5432
      dbname: dbprojetopaco
      schema: public
      threads: 1
      keepalives_idle: 0